Garden/Controllers/PlotsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Garden.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Garden.Controllers
{
  public class PlotsController : Controller
  {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly GardenContext _db;

    public PlotsController(UserManager<ApplicationUser> userManager, GardenContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Plot> model = _db.Plots.ToList();
      return View(model);
    }
    [Authorize]
    public async Task<ActionResult> Create()
    {
      // ViewBag.PlotId = new SelectList(_db.Plots, "PlotId", "PlotName");
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userItems = _db.Plots.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Plot plot)
    {
      _db.Plots.Add(plot);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = plot.PlotId});
    }

    public ActionResult Details(int id)
    {
      var thisPlot = _db.Plots.FirstOrDefault(model => model.PlotId == id);
      int zipcode = thisPlot.ZipCode;
      ViewBag.thisZipZone = ZipZone.Get(zipcode);

      return View(thisPlot);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisPlot = _db.Plots.FirstOrDefault(plot => plot.PlotId == id);
      return View(thisPlot);
    }

    [HttpPost]
    public ActionResult Edit(Plot plot)
    {
      _db.Entry(plot).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisPlot = _db.Plots.FirstOrDefault(plot => plot.PlotId == id);
      return View(thisPlot);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPlot = _db.Plots.FirstOrDefault(plot => plot.PlotId == id);
      _db.Plots.Remove(thisPlot);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Garden/Controllers/SeedsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Garden.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;


namespace Garden.Controllers
{
  public class SeedsController : Controller
  {
    // private readonly GardenContext _db;

    // public SeedsController(GardenContext db)
    // {
    //   _db = db;
    // }
    public IActionResult Index()
    {
      var seeds = Seed.Get();
      return View(seeds);
    }
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Seed seed)
    {
      Seed.Post(seed);
      return RedirectToAction("Details", new {id = seed.SeedId});
    }


    public IActionResult Details(int id)
    {
      var model = Seed.GetDetails(id);
      return View(model);
    }


    public IActionResult Edit (int id)
    {
      var model = Seed.GetDetails(id);
      return View(model);
    }


    [HttpPost]
    public IActionResult Edit(int id, Seed seed)
    {
      seed.SeedId = id;
      Seed.Put(seed);
      return RedirectToAction("Details", new {id = seed.SeedId});
    }

    public IActionResult Delete(int id)
    {
      var model = Seed.GetDetails(id);
      return View(model);
    }


    public IActionResult DeleteConfirmed(int id)
    {
      Seed.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

Garden/Controllers/SquarefootsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Garden.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Garden.Controllers
{
  
  public class SquarefootsController : Controller
  {
    private readonly GardenContext _db;

    public SquarefootsController(GardenContext db)
    {
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Squarefoot> model = _db.Squarefoots.ToList();
      return View(model);
    }
    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Squarefoot squarefoot)
    {
      _db.Squarefoots.Add(squarefoot);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisSquarefoot = _db.Squarefoots;
      return View(thisSquarefoot);
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisSquarefoot = _db.Squarefoots.FirstOrDefault(squarefoot => squarefoot.SquarefootId == id);
      return View(thisSquarefoot);
    }

    [HttpPost]
    public ActionResult Edit(Squarefoot squarefoot)
    {
      _db.Entry(squarefoot).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisSquarefoot = _db.Squarefoots.FirstOrDefault(squarefoot => squarefoot.SquarefootId == id);
      return View(thisSquarefoot);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisSquarefoot = _db.Squarefoots.FirstOrDefault(squarefoot => squarefoot.SquarefootId == id);
      _db.Squarefoots.Remove(thisSquarefoot);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Garden/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garden</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/scss/custom.css" />
    <link rel="stylesheet" href="~/scss/custom.css.map" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Garden</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Plots" asp-action="Index">Plots</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Squarefoots" asp-action="Index">Squarefoots</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Seeds" asp-action="Index">Seeds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="LearningZone">Learning Zone</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
            <button id="myBtn" title="Go to top">^</button>
    </div>

    <footer class="border-top footer bg-white text-muted">
        <div class="container">
            &copy; 2021 - Garden - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
<script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Garden/Views/Shared/_LayoutLearning.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Garden</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/learning.css" />

</head>

<body id = "body-learning">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Garden</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Plots" asp-action="Index">Plots</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Seeds" asp-action="Index">Seeds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
    </div>
        <button id="myBtn" title="Go to top">^</button>

        </main>
    <footer class="border-top footer bg-white text-muted">
        <div class="container">
            &copy; 2021 - Garden - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>